name: smart_meeting_companion
description: A smart meeting companion app
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  provider: ^6.0.5
  shared_preferences: ^2.0.15
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.0
  file_picker: ^5.2.6
  audio_session: ^0.1.13
  record: ^4.4.0
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  flutter_markdown: ^0.6.18
  flutter_dotenv: ^5.0.2
  json_annotation: ^4.8.0
  flutter_local_notifications: ^15.1.1
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
